/**
 * This class file was automatically generated by jASN1 v1.8.1 (http://www.openmuc.org)
 */

package com.veon.rafm.roamingfraud.processors.NrtrdeDecodeProcessor.nrtrde;


public class BCDString extends org.openmuc.jasn1.ber.types.BerOctetString {

	private static final long serialVersionUID = 1L;

	public BCDString() {
	}

	public BCDString(byte[] value) {
		super(value);
	}

}
