/**
 * This class file was automatically generated by jASN1 v1.8.1 (http://www.openmuc.org)
 */

package com.veon.rafm.roamingfraud.processors.NrtrdeDecodeProcessor.nrtrde;

import org.openmuc.jasn1.ber.types.*;


public class NumberString extends BerOctetString {

	private static final long serialVersionUID = 1L;

	public NumberString() {
	}

	public NumberString(byte[] value) {
		super(value);
	}

}
